version: 2
updates:
  # CI workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # setup-zeitgeist
  - package-ecosystem: "github-actions"
    directory: "/setup-zeitgeist"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
