name: test-bom-action

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      bom: ${{ steps.filter.outputs.bom }}

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            bom:
              - 'setup-bom/**'
              - '.github/workflows/test-setup-bom.yml'

  test_bom_action:
    needs: changes
    if: ${{ needs.changes.outputs.bom == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install bom and test presence in path
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install bom
        uses: ./setup-bom
      - name: Check install!
        run: bom version
      - name: Check root directory
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi
        shell: bash

  test_bom_action_custom_dir_root:
    runs-on: ${{ matrix.os }}
    needs: changes
    if: ${{ needs.changes.outputs.bom == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install Custom bom and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install bom
        uses: ./setup-bom
        with:
          install-dir: /usr/bin
          use-sudo: true
      - name: Check install!
        run: bom version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which bom)") == /usr/bin ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_bom_action_custom_dir:
    runs-on: ${{ matrix.os }}
    needs: changes
    if: ${{ needs.changes.outputs.bom == 'true' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install Custom path bom and test presence in path
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install bom
        uses: ./setup-bom
        with:
          install-dir: "$HOME/.bomtest"
      - name: Check install!
        run: bom version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which bom)") == "$HOME/.bomtest" ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_bom_action_wrong:
    runs-on: ${{ matrix.os }}
    needs: changes
    if: ${{ needs.changes.outputs.bom == 'true' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Try to install a wrong bom
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install bom
        uses: ./setup-bom
        with:
          bom-release: 'honk'
        continue-on-error: true
